blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='home'),
    path('create', BlogCreateView.as_view(), name='create'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, client_form, \
    HomeListView

app_name = MailingConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('list', MailingListView.as_view(), name='mailing_list'),
    path('create/', MailingCreateView.as_view(), name='create'),
    path('update/<int:pk>/', MailingUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='delete'),

    path('client_form', client_form, name='client_form'),

]
# handler_404 =

mailing/models.py
import colorama
from django.conf import settings
from django.db import models, connection
from django.views import generic

NULLABLE = {'null': True, 'blank': True}

STATUS_CHOICES = (
    ('Завершена', 'Завершена'),
    ('Создана', 'Создана'),
    ('Запущена', 'Запущена'),
)

FREQUENCY_CHOICES = (
    ('1', 'раз в день'),
    ('7', 'раз в неделю'),
    ('30', 'раз в месяц'),
)


class Truncate:
    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            name_table = f'{cls.__module__.split(".")[0]}_{cls.__name__.lower()}'
            cursor.execute(f'TRUNCATE TABLE "{name_table}" RESTART IDENTITY CASCADE')
            print(colorama.Fore.GREEN + f'Таблица "{name_table}" очищена!' \
                  + colorama.Fore.RESET)


class Client(models.Model, Truncate):
    email = models.EmailField(verbose_name='Контактный email')
    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(verbose_name='Комментарий')

    def __str__(self):
        return f'{self.email} - {self.full_name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailing(models.Model, Truncate):
    time_mailing = models.TimeField(verbose_name='Время рассылки')
    end_datatime_mailing = models.DateTimeField(verbose_name='Дата и время окончания рассылки')
    frequency = models.CharField(choices=FREQUENCY_CHOICES, default='1',
                                 verbose_name='Периодичность: раз в день, раз в неделю, раз в месяц')
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='Создана', verbose_name='Статус рассылки')
    сlient_key = models.ManyToManyField(Client, verbose_name='Пользователь', related_name='client')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')

    def __str__(self):
        return (
            f'{colorama.Fore.LIGHTYELLOW_EX + self.status + colorama.Fore.RESET} - '
            f'{colorama.Fore.GREEN + self.end_datatime_mailing.strftime("%d-%m-%Y %H:%M") + colorama.Fore.RESET} / '
            f'{colorama.Fore.MAGENTA + self.time_mailing.strftime("%H:%M") + colorama.Fore.RESET}')

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ['-status', 'end_datatime_mailing']
        permissions = [
            (
                'set_status',
                'Can publish mailing'
            )
        ]


class MessageMailing(models.Model, Truncate):
    topic = models.CharField(max_length=100, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Тело письма')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылки')

    def __str__(self):
        return f'Тема: {self.topic} - Сообщение: {self.body}'

    class Meta:
        verbose_name = 'Сообщение для рассылки'
        verbose_name_plural = 'Сообщение для рассылок'


class LogsMailing(models.Model, Truncate):
    date = models.DateTimeField(verbose_name='Дата и время последней попытки')
    status = models.CharField(max_length=100, verbose_name='Статус попытки')
    mail_response = models.TextField(max_length=100, verbose_name='Ответ почтового сервера')

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')

    def __str__(self):
        return f'Тема:{self.status} - {self.date}'

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылки'

mailing/forms.py
import datetime

from django import forms
from django.forms import widgets

from mailing.models import Mailing, MessageMailing, Client


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        # fields = '__all__'
        exclude = ('owner',)

        widgets = {
            'time_mailing': forms.TimeInput(
                format='%H:%M:%S',
                attrs={'type': 'time',
                       # 'min': datetime.datetime.today().strftime('%H:%M'),
                       'value': datetime.datetime.today().strftime('%H:%M')}),

            'end_datatime_mailing': forms.DateInput(
                format='%Y-%m-%d %H:%M:%S',
                attrs={'type': 'datetime-local',
                       'min': f'{datetime.datetime.today().strftime("%Y-%m-%d")}',
                       'value': f'{datetime.datetime.today().strftime("%Y-%m-%d")} {datetime.datetime.today().strftime("%H:%M")}'
                       }),

        }


class MessageMailingForm(StyleFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MessageMailingForm, self).__init__(*args, **kwargs)

        # self.fields['body'].disabled = True

    class Meta:
        model = MessageMailing
        fields = '__all__'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

mailing/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.forms import inlineformset_factory, formset_factory, modelformset_factory
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from blog.models import Blog
from mailing.forms import MailingForm, MessageMailingForm, ClientForm
from mailing.models import Mailing, MessageMailing, Client, LogsMailing
from users.models import User


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Класс создания рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if not self.request.user.is_superuser:
            # Отключить поле status
            form.fields["status"].disabled = True
        return form

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MailingFormset = inlineformset_factory(Mailing, MessageMailing, form=MessageMailingForm, extra=1,
                                               can_delete=False)
        if self.request.method == 'POST':
            context_data['formset'] = MailingFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MailingFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class MailingListView(LoginRequiredMixin, ListView):
    """Класс отображения рассылок"""
    model = Mailing

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # if self.request.user == self.object.owner:
        #     print('sdfsds')
        #     pass

        if self.request.user.has_perm("mailing.view_mailing"):
            return context_data

        return context_data


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Класс редактирования рассылок"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        MailingFormset = inlineformset_factory(Mailing, MessageMailing, form=MessageMailingForm, extra=1,
                                               can_delete=False)
        context_data['button_add_client'] = True

        if self.request.method == 'POST':
            context_data['formset'] = MailingFormset(self.request.POST, instance=self.object)
        elif self.object.owner == self.request.user:
            context_data['formset'] = MailingFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        """ Сохраняет данные из formset """
        formset = self.get_context_data()['formset']

        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        else:
            if self.object.owner != self.request.user:
                pass
            else:
                return self.form_invalid(form)

        return super().form_valid(form)

    def get_form(self, form_class=None, **kwargs):
        """ Если у пользователя нет прав на редактирование поля (*делаем не активным), удаляем его из формы"""
        form = super().get_form(form_class)
        if self.object.owner != self.request.user:
            mailing_fields = [fiel_key for fiel_key in form.fields.keys()]
            for field in mailing_fields:
                if not self.request.user.has_perm(f'mailing.set_{field}'):
                    if not field == 'status':
                        form.fields[field].disabled = True
                        # del form.fields[field]
        return form


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    """Класс удаления рассылок"""
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')


def client_form(request):
    if request.method == 'POST':
        email = request.POST['email']
        full_name = request.POST['full_name']
        comment = request.POST['comment']
        Client.objects.create(email=email, full_name=full_name, comment=comment)

    return HttpResponseRedirect(reverse('mailing:create'))


class HomeListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = 'mailing/home.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['title'] = 'New-Mailing - это отличный вариант отправки рассылок, который вы бы хотели'
        context['qty_mailing'] = Mailing.objects.filter(owner=self.request.user).count
        context['qty_client'] = Client.objects.all().count
        context['qty_mailing_all'] = Mailing.objects.all().count
        context['LogsMailing_success'] = LogsMailing.objects.filter(status='Успешно').count
        context['LogsMailing_error'] = LogsMailing.objects.filter(status='Ошибка').count
        context['LogsMailing_result'] = LogsMailing.objects.filter(status='Успешно').count


        if self.request.user.has_perm('mailing.view_mailing'):
            context['activ_mailing'] = Mailing.objects.filter(Q(status='Создана') | Q(status='Запущена')).count
        else:
            context['activ_mailing'] = Mailing.objects.filter(owner=self.request.user).filter(
                Q(status='Создана') | Q(status='Запущена')).count
        context['photo_blog'] = Blog.objects.all()[:3]

        return context

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ title }}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'mailing/includes/inc_catalog_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title1 }}</h1>
    <p class="lead">{{title}}</p>
</div>


{% block content%}


{% endblock %}


<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            New-Mailing
            <small class="d-block mb-3 text-muted">&copy; 2024</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}


{% block content%}
<div class="container  py-3">
    <div class="mb-5 ">
        <div class="text-center">

            <form method="post">
                {% csrf_token %}
                <H1>Вы хотите удалить рассылку?</H1>
                {% for object in object.сlient_key.all %}
                <H2>Почта: {{object}}</H2>
                {% endfor %}
                <H2>"{{object.end_datatime_mailing}}"</H2>
                <br>
                <button class="btn btn-outline-danger">Удалить</button>
                <a class="btn btn-outline-warning" href="{% url 'mailing:mailing_list' %}">Отмена</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends '/base.html' %}}


{% block content%}

<div class="container-sm py-3">


</div>

{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}


{% block content%}


<div class="container">

    {% if not button_add_client%}
    <div class="d-grid gap-2 col-2 mx-auto">
        <div class="row justify-content-center">
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal"
                    data-bs-whatever="@mdo">
                Добавить клиента
            </button>
        </div>
    </div>
    <br>
     {% endif %}

    <form method="post" enctype="multipart/form-data">
        <div class="row justify-content-center">
            <div class="col-5">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title">
                            {% if object.date_create%}
                            Изменение рассылки
                            {% else %}
                            Добавление рассылки
                            {% endif %}
                        </h2>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}


                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>


            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title">
                            Сообщение для рассылки:
                        </h2>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}

                        {{ form.as_p }}

                        {% if not formloop.last %}
                        <br>
                        {% endif %}

                        {% endfor %}
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
    </form>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Добавить клиента</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>


            <form action="/client_form" name="client_form" method="post" class="was-validated"
                  enctype="multipart/form-data">
                <div class="modal-body">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Адресс почты:</label>'

                        <input name="email" type="email" class="form-control" id="exampleFormControlInput1"
                               placeholder="name@mail.ru" maxlength="60" required>
                        <div class="invalid-tooltip position-relative">
                            Пожалуйста, введите электронную почту!
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="exampleFormControlInput2" class="form-label">Полное имя:</label>
                        <input name="full_name" type="text" class="form-control" id="exampleFormControlInput2"
                               placeholder="Василий" maxlength="150"
                               required>
                        <div class="invalid-tooltip position-relative">
                            Пожалуйста, введите свое имя.
                        </div>
                    </div>


                    <div class="form-outline" data-mdb-input-init>
                        <label class="form-label" for="textAreaExample">Комментарий:</label>
                        <textarea name="comment" class="form-control" id="textAreaExample" rows="4"></textarea>
                    </div>


                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </form>


        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}}
{% load static%}

{% block content%}


<div class="container py-3">
    <div class="row row-cols-1 row-cols-md-4 mb-3 text-center">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">
                    <style>
                        .data {
                        color: rgb(0, 0, 0);
                        font-size:35px;
                        text-shadow: rgb(204, 204, 204) 0px 1px 0px, rgb(201, 201, 201) 0px 2px 0px, rgb(187, 187, 187) 0px 3px 0px, rgb(185, 185, 185) 0px 4px 0px, rgb(170, 170, 170) 0px 5px 0px, rgba(0, 0, 0, 0.1) 0px 6px 1px, rgba(0, 0, 0, 0.1) 0px 0px 5px, rgba(0, 0, 0, 0.3) 0px 1px 3px, rgba(0, 0, 0, 0.15) 0px 3px 5px, rgba(0, 0, 0, 0.2) 0px 5px 10px, rgba(0, 0, 0, 0.2) 0px 10px 10px, rgba(0, 0, 0, 0.1) 0px 20px 20px;
                        }
                    </style>
                    <div class="data">{% now "j F Y" %}</div>
                </th>
                <th scope="col">
                    <div class="watch">
                        <script type="text/javascript"
                                src="https://bootstraptema.ru/plugins/2015/x-tag/x-tag-core.min.js"></script>
                        <style>
                            x-clock {
                            color: rgb(0, 0, 0);
                            font-size:35px;
                            text-shadow: rgb(204, 204, 204) 0px 1px 0px, rgb(201, 201, 201) 0px 2px 0px, rgb(187, 187, 187) 0px 3px 0px, rgb(185, 185, 185) 0px 4px 0px, rgb(170, 170, 170) 0px 5px 0px, rgba(0, 0, 0, 0.1) 0px 6px 1px, rgba(0, 0, 0, 0.1) 0px 0px 5px, rgba(0, 0, 0, 0.3) 0px 1px 3px, rgba(0, 0, 0, 0.15) 0px 3px 5px, rgba(0, 0, 0, 0.2) 0px 5px 10px, rgba(0, 0, 0, 0.2) 0px 10px 10px, rgba(0, 0, 0, 0.1) 0px 20px 20px;
                            }
                        </style>
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-6 col-lg-offset-3">
                                    <div class="text-center">
                                        <x-clock></x-clock>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <script>
                            xtag.register('x-clock', {
                             lifecycle: {
                             created: function(){
                             this.start();
                             }
                             },
                             methods: {
                             start: function(){
                             this.update();
                             this.xtag.interval = setInterval(this.update.bind(this), 1000);
                             },
                             stop: function(){
                             this.xtag.interval = clearInterval(this.xtag.interval);
                             },
                             update: function(){
                             this.textContent = new Date().toLocaleTimeString();
                             }
                             },
                             events: {
                             tap: function(){
                             if (this.xtag.interval) this.stop();
                             else this.start();
                             }
                             }
                            });
                        </script>
                    </div>
                </th>
            </tr>
            </thead>

            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Дата и время окончания рассылки</th>
                <th scope="col">Время рассылки</th>
                <th scope="col">Отправка</th>
                <th scope="col">Клиент</th>
                <th scope="col">Статус</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>


            {% for object in object_list %}
            {% if perms.mailing.view_mailing or request.user == object.owner %}
            <tr>
                <th scope="row">{{object.pk}}</th>
                <td class=" text-center">{{object.end_datatime_mailing}}</td>
                <td>{{object.time_mailing}}</td>
                <td>{{object.frequency}}</td>
                <td>
                    {% for object in object.сlient_key.all %}
                    {{object}} <br>
                    {% endfor%}
                </td>

                <td style="width:100px">
                    {% if object.status == 'Создана' %}
                    <img src="/media/status_active.png" style="max-width: 30%; height: auto;">
                    {% elif object.status == 'Запущена'%}
                    <img src="/media/status_work.png" style="max-width: 30%; height: auto;">
                    {% elif object.status == 'Завершена'%}
                    <img src="/media/status_inactive.png" style="max-width: 30%; height: auto;">
                    {% endif %}
                </td>

                <td class="py-2">
                    <div class="container">

                        <div class="row">
                            <div class="col m-0 p-0">
                                {% if perms.mailing.change_mailing or object.owner == request.user %}
                                <a href="{% url 'mailing:update' object.pk %}"
                                   class="btn btn-outline-secondary btn-sm">Изменить</a>
                                {% endif %}
                            </div>
                            <div class="col m-0 p-0">
                                {% if perms.mailing.delete_mailing or object.owner == request.user %}
                                <a href="{% url 'mailing:delete' object.pk %}" class="btn-basket btn btn-sm">
                                    <img src="/media/delete.svg" style="width: 100%; height: 1.2em">
                                </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </td>
            </tr>

            {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>


<style>
    .btn-basket{
         border: 1px solid black;
    }
     .btn-basket:hover{
      border: 1px solid black;
            -webkit-filter: sepia(1) hue-rotate(320deg) saturate(10);
            filter: sepia(1) hue-rotate(320deg) saturate(10);
    }
</style>

{% endblock %}