blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='home'),
    path('create', BlogCreateView.as_view(), name='create'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models

from mailing.models import Truncate

NULLABLE = {
    'null': 'True',
    'blank': 'True',
}


class Blog(models.Model, Truncate):
    title = models.CharField(max_length=150, verbose_name='Название')
    slug = models.CharField(**NULLABLE, max_length=150, verbose_name='slug')
    body = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='Изображение')
    date_create = models.DateTimeField(**NULLABLE, auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    count_views = models.IntegerField(**NULLABLE, default=0, verbose_name='Количество просмотров')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')

    def __str__(self):
        return f'{self.title} {self.date_create}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блог'
        ordering = ['date_create']
        permissions = [
            ('set_is_published', 'Может публиковать товары'),
        ]

blog/forms.py
from django import forms

from blog.models import Blog
from mailing.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'body', 'preview',)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView

from blog.forms import BlogForm
from blog.models import Blog


class BlogListView(ListView):
    model = Blog


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['title1'] = 'Создание контента для блога'
        return context

    def form_valid(self, form):
        self.object = form.save()
        if self.request.user.is_authenticated:
            self.object.owner = self.request.user
            self.object.save()
        return super().form_valid(form)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}


{% block content%}
<div class="col-6 mx-auto">
    <div class="row">
        <div class="card">

            <div class="card-header text-center">
                <h5 class="card-title">{{ object.title }}</h5>
            </div>

            <div class="row align-items-start">
                <div class="col">
                    <div class="card mb-3 mt-3 rounded  d-block" style="max-width: 500px;">
                        <img src="/media/{{ object.preview }}" class="img-fluid"/>
                    </div>
                </div>

                <div class="col">
                    <div class="card mb-3 mt-3 rounded">
                        <h5 class="card-title text-center">Описание</h5>
                    </div>

                    <div class="alert alert-success " role="alert">
                        <p class="mb-0"> {{ object.body }}</p>
                        <hr>
                        <b>Просмотры: {{ object.count_views }}</b>
                    </div>

                </div>
            </div>

            <div class="card-footer text-muted text-center">
                <p class="card-text"><small class="text-muted">{{object.date_create}}</small></p>
            </div>

        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}


{% block content%}
<div class="container py-3">

    <div class="col-12">

        <div class="row justify-content-center">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {% if object.slug%}
                            <button type="submit" class="btn btn-success">Изменить</button>
                            {% else %}
                            <button type="submit" class="btn btn-success">Создать</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}


{% block content%}

<div class="container py-3">
    {% if user.is_authenticated %}
    <div class="mb-5">
        <a class="btn btn-primary" href="{% url 'blog:create' %}">Создать статью</a>
    </div>
    {% endif %}
    <div class="row row-cols-1 row-cols-md-4 mb-3 text-center">

        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-success">Автор</strong>
                    <h3 class="mb-0">Заголовок поста</h3>
                    <div class="mb-1 text-muted">11 Ноября</div>
                    <p class="mb-auto">Это более широкая карточка с вспомогательным текстом ниже в качестве
                        естественного перехода к дополнительному контенту.</p>
                    <a href="#" class="stretched-link">Продолжить чтение</a>
                </div>
                <div class="col-auto d-none d-lg-block">

                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg"
                         role="img" aria-label="Placeholder: Эскиз" preserveAspectRatio="xMidYMid slice"
                         focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"></rect>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">Эскиз</text>
                    </svg>

                </div>
            </div>
        </div>

        {% for object in object_list %}
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static" style="border: 1px solid black;">

                    <div class="row p-0 m-0">
                        <img class="p-1 m-0" src="/media/blog/views.png" style="width:7%; height:auto"> {{object.count_views}}
                    </div>

                    <strong class="d-inline-block mb-2 text-success">{{object.owner}}</strong>
                    <h3 class="mb-0">{{object.title}}</h3>
                    <div class="mb-1 text-muted">{{object.date_create|date:'j E'}}</div>
                    <p class="mb-auto">{{object.body}}</p>
                    <a href="{% url 'blog:view' object.pk%}" class="stretched-link">Продолжить чтение</a>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <img class="p-1" style="width:200px; height:250px; border: 2px solid black;"
                         src="/media/{{object.preview}}">
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

{% endblock %}