blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='home'),
    path('create', BlogCreateView.as_view(), name='create'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.services import is_active_key_registration
from users.views import RegisterView, UsersListView, change_task_status

app_name = UsersConfig.name

urlpatterns = [
    path('login', cache_page(60)(LoginView.as_view(template_name='users/login.html')), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('client', UsersListView.as_view(), name='client'),
    path('key-registration/<str:key>', is_active_key_registration, name='key_registration'),

    path('task-status/<int:pk>/<str:status>/', change_task_status, name='change_task_status'),
]

users/models.py
from django.contrib.auth.models import AbstractUser

from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')

    registration_key = models.CharField(max_length=100, verbose_name='Регистрационный ключ')
    is_active = models.BooleanField(default=False, verbose_name='Флаг верификации')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        """Сортировка"""
        ordering = ['-is_active', 'email']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import CheckboxInput

from mailing.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(UserCreationForm, StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(forms.ModelForm,StyleFormMixin):
    class Meta:
        model = User
        fields = '__all__'
        widgets = {
            'is_active': forms.CheckboxInput()
        }

        # widgets = {
        #     'is_anything_required': CheckboxInput(attrs={'class': 'required checkbox form-control'}),
        # }

users/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView

from users.forms import UserRegisterForm, UserForm
from users.models import User
from users.services import get_send_mail


class RegisterView(CreateView):
    """Регистрация пользователя"""
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        self.object = form.save()
        self.object.save()
        while True:
            random_key_registration = ''.join([str(random.randint(0, 9)) for _ in range(12)])
            if form.is_valid():
                if User.objects.filter(registration_key=random_key_registration):
                    continue
                else:
                    new_key = form.save()
                    try:
                        new_key.registration_key = random_key_registration
                        new_key.save()
                        get_send_mail(self.object.email, random_key_registration)
                    except:
                        pass

                    return super().form_valid(form)
        return super().form_valid(form)


class UsersListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    form_class = UserForm
    success_url = '/'
    permission_required = 'users.view_user'

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     """Если авторизованный пользователь superuser то в списке пользователей удалять строку админа """
    #     context = super().get_context_data(**kwargs)
    #     if not self.request.user.is_superuser:
    #         context['object_list'] = User.objects.filter(is_staff=False).filter(is_superuser=False)
    #     else:
    #         context['object_list'] = User.objects.exclude(email=self.request.user)
    #     return context




def change_task_status(request, pk, status):
    task = User.objects.get(pk=pk)
    task.is_active = status
    task.save()
    return redirect('users:client')

users/templates/users/login.html
{% extends 'mailing/base.html' %}


{% block content%}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row justify-content-center">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title">
                            Вход
                        </h2>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="btn btn-primary">Войти</button>
                        <a class="p-2 " href="#">Забыли пароль?</a>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}


{% block content%}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row justify-content-center">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title">
                            Регистрация
                        </h2>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>


        </div>
    </form>
</div>

{% endblock %}

users/templates/users/success_registration.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header text-center">
                <h1>Верификацию </h1>
            </div>
            <div class="card-body alert alert-success" class="" role="alert">
                <H5>Регистрация завершена, аккаунт активирован! Для продолжения перейдите по <a href="{% url 'users:login' %}">ссылке</a></H5>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}}


{% block content%}

<form method="post">
    <div class="container py-3">
        <div class="row row-cols-1 row-cols-md-4 mb-3 text-center">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">Пользователь</th>
                    <th scope="col">Статус</th>
                </tr>
                </thead>
                {% csrf_token %}
                {{ form.as_p }}
                <tbody>
                <tr>
                    <td>
                        {{object.email}}
                    </td>
                    <td>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>
                            <label class="form-check-label" for="flexSwitchCheckChecked">Декактивировать
                                пользователя?</label>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <button type="submit">Save</button>
</form>


{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}}

{% block content%}
<div class="container py-3">
    <div class="row row-cols-1 row-cols-md-4 mb-3 text-center">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Пользователь</th>
                <th scope="col">Статус</th>
            </tr>
            </thead>
            {% for object in object_list %}
            <tbody>
            <tr>
                <td>
                    {{ object.email }}
                </td>

                {% if 'Менеджер' in object.groups.first.name %}
                <td class="sorting_1">
                    <span class="badge badge-pill badge-primary"
                          style="color:#fff;background-color: #007bff">Moder</span>
                </td>
                {% elif object.is_superuser %}
                <td class="sorting_1">
                    <span class="badge badge-pill badge-primary"
                          style="color:#fff;background-color: #dc3545">Admin</span>
                </td>
                {% else %}
                <td class="sorting_1">
                    <span class="badge badge-pill badge-primary" style="color:#fff;background-color: #dc3545"></span>
                </td>
                {% endif %}
                <td>


                    <div class="form-check form-switch">
                        {% if object.is_superuser %}
                        <div onclick="location.href='{% url 'users:change_task_status' object.pk True %}'">
                            <input class="form-check-input" type="checkbox" checked disabled>
                        </div>
                        {% elif object.is_active %}
                        <div onclick="location.href='{% url 'users:change_task_status' object.pk False %}'">
                            <input class="form-check-input" type="checkbox" checked>
                        </div>
                        {% else %}
                        <div onclick="location.href='{% url 'users:change_task_status' object.pk True %}'">
                            <input class="form-check-input" type="checkbox">
                        </div>
                        {%endif%}
                        <label class="form-check-label">Деактивировать пользователя?</label>
                    </div>


                </td>
            </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}