blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='home'),
    path('create', BlogCreateView.as_view(), name='create'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, client_form, \
    HomeListView

app_name = MailingConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('list', MailingListView.as_view(), name='mailing_list'),
    path('create/', MailingCreateView.as_view(), name='create'),
    path('update/<int:pk>/', MailingUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='delete'),

    path('client_form', client_form, name='client_form'),

]
# handler_404 =

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.services import is_active_key_registration
from users.views import RegisterView, UsersListView, change_task_status

app_name = UsersConfig.name

urlpatterns = [
    path('login', cache_page(60)(LoginView.as_view(template_name='users/login.html')), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('client', UsersListView.as_view(), name='client'),
    path('key-registration/<str:key>', is_active_key_registration, name='key_registration'),

    path('task-status/<int:pk>/<str:status>/', change_task_status, name='change_task_status'),
]

mailing/models.py
import colorama
from django.conf import settings
from django.db import models, connection
from django.views import generic

NULLABLE = {'null': True, 'blank': True}

STATUS_CHOICES = (
    ('Завершена', 'Завершена'),
    ('Создана', 'Создана'),
    ('Запущена', 'Запущена'),
)

FREQUENCY_CHOICES = (
    ('1', 'раз в день'),
    ('7', 'раз в неделю'),
    ('30', 'раз в месяц'),
)


class Truncate:
    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            name_table = f'{cls.__module__.split(".")[0]}_{cls.__name__.lower()}'
            cursor.execute(f'TRUNCATE TABLE "{name_table}" RESTART IDENTITY CASCADE')
            print(colorama.Fore.GREEN + f'Таблица "{name_table}" очищена!' \
                  + colorama.Fore.RESET)


class Client(models.Model, Truncate):
    email = models.EmailField(verbose_name='Контактный email')
    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(verbose_name='Комментарий')

    def __str__(self):
        return f'{self.email} - {self.full_name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailing(models.Model, Truncate):
    time_mailing = models.TimeField(verbose_name='Время рассылки')
    end_datatime_mailing = models.DateTimeField(verbose_name='Дата и время окончания рассылки')
    frequency = models.CharField(choices=FREQUENCY_CHOICES, default='1',
                                 verbose_name='Периодичность: раз в день, раз в неделю, раз в месяц')
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='Создана', verbose_name='Статус рассылки')
    сlient_key = models.ManyToManyField(Client, verbose_name='Пользователь', related_name='client')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')

    def __str__(self):
        return (
            f'{colorama.Fore.LIGHTYELLOW_EX + self.status + colorama.Fore.RESET} - '
            f'{colorama.Fore.GREEN + self.end_datatime_mailing.strftime("%d-%m-%Y %H:%M") + colorama.Fore.RESET} / '
            f'{colorama.Fore.MAGENTA + self.time_mailing.strftime("%H:%M") + colorama.Fore.RESET}')

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ['-status', 'end_datatime_mailing']
        permissions = [
            (
                'set_status',
                'Can publish mailing'
            )
        ]


class MessageMailing(models.Model, Truncate):
    topic = models.CharField(max_length=100, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Тело письма')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылки')

    def __str__(self):
        return f'Тема: {self.topic} - Сообщение: {self.body}'

    class Meta:
        verbose_name = 'Сообщение для рассылки'
        verbose_name_plural = 'Сообщение для рассылок'


class LogsMailing(models.Model, Truncate):
    date = models.DateTimeField(verbose_name='Дата и время последней попытки')
    status = models.CharField(max_length=100, verbose_name='Статус попытки')
    mail_response = models.TextField(max_length=100, verbose_name='Ответ почтового сервера')

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')

    def __str__(self):
        return f'Тема:{self.status} - {self.date}'

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылки'

users/models.py
from django.contrib.auth.models import AbstractUser

from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')

    registration_key = models.CharField(max_length=100, verbose_name='Регистрационный ключ')
    is_active = models.BooleanField(default=False, verbose_name='Флаг верификации')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        """Сортировка"""
        ordering = ['-is_active', 'email']

mailing/forms.py
import datetime

from django import forms
from django.forms import widgets

from mailing.models import Mailing, MessageMailing, Client


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        # fields = '__all__'
        exclude = ('owner',)

        widgets = {
            'time_mailing': forms.TimeInput(
                format='%H:%M:%S',
                attrs={'type': 'time',
                       # 'min': datetime.datetime.today().strftime('%H:%M'),
                       'value': datetime.datetime.today().strftime('%H:%M')}),

            'end_datatime_mailing': forms.DateInput(
                format='%Y-%m-%d %H:%M:%S',
                attrs={'type': 'datetime-local',
                       'min': f'{datetime.datetime.today().strftime("%Y-%m-%d")}',
                       'value': f'{datetime.datetime.today().strftime("%Y-%m-%d")} {datetime.datetime.today().strftime("%H:%M")}'
                       }),

        }


class MessageMailingForm(StyleFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MessageMailingForm, self).__init__(*args, **kwargs)

        # self.fields['body'].disabled = True

    class Meta:
        model = MessageMailing
        fields = '__all__'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

mailing/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.forms import inlineformset_factory, formset_factory, modelformset_factory
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from blog.models import Blog
from mailing.forms import MailingForm, MessageMailingForm, ClientForm
from mailing.models import Mailing, MessageMailing, Client, LogsMailing
from users.models import User


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Класс создания рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if not self.request.user.is_superuser:
            # Отключить поле status
            form.fields["status"].disabled = True
        return form

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MailingFormset = inlineformset_factory(Mailing, MessageMailing, form=MessageMailingForm, extra=1,
                                               can_delete=False)
        if self.request.method == 'POST':
            context_data['formset'] = MailingFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MailingFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class MailingListView(LoginRequiredMixin, ListView):
    """Класс отображения рассылок"""
    model = Mailing

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # if self.request.user == self.object.owner:
        #     print('sdfsds')
        #     pass

        if self.request.user.has_perm("mailing.view_mailing"):
            return context_data

        return context_data


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Класс редактирования рассылок"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        MailingFormset = inlineformset_factory(Mailing, MessageMailing, form=MessageMailingForm, extra=1,
                                               can_delete=False)
        context_data['button_add_client'] = True

        if self.request.method == 'POST':
            context_data['formset'] = MailingFormset(self.request.POST, instance=self.object)
        elif self.object.owner == self.request.user:
            context_data['formset'] = MailingFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        """ Сохраняет данные из formset """
        formset = self.get_context_data()['formset']

        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        else:
            if self.object.owner != self.request.user:
                pass
            else:
                return self.form_invalid(form)

        return super().form_valid(form)

    def get_form(self, form_class=None, **kwargs):
        """ Если у пользователя нет прав на редактирование поля (*делаем не активным), удаляем его из формы"""
        form = super().get_form(form_class)
        if self.object.owner != self.request.user:
            mailing_fields = [fiel_key for fiel_key in form.fields.keys()]
            for field in mailing_fields:
                if not self.request.user.has_perm(f'mailing.set_{field}'):
                    if not field == 'status':
                        form.fields[field].disabled = True
                        # del form.fields[field]
        return form


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    """Класс удаления рассылок"""
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')


def client_form(request):
    if request.method == 'POST':
        email = request.POST['email']
        full_name = request.POST['full_name']
        comment = request.POST['comment']
        Client.objects.create(email=email, full_name=full_name, comment=comment)

    return HttpResponseRedirect(reverse('mailing:create'))


class HomeListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = 'mailing/home.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['title'] = 'New-Mailing - это отличный вариант отправки рассылок, который вы бы хотели'
        context['qty_mailing'] = Mailing.objects.filter(owner=self.request.user).count
        context['qty_client'] = Client.objects.all().count
        context['qty_mailing_all'] = Mailing.objects.all().count
        context['LogsMailing_success'] = LogsMailing.objects.filter(status='Успешно').count
        context['LogsMailing_error'] = LogsMailing.objects.filter(status='Ошибка').count
        context['LogsMailing_result'] = LogsMailing.objects.filter(status='Успешно').count


        if self.request.user.has_perm('mailing.view_mailing'):
            context['activ_mailing'] = Mailing.objects.filter(Q(status='Создана') | Q(status='Запущена')).count
        else:
            context['activ_mailing'] = Mailing.objects.filter(owner=self.request.user).filter(
                Q(status='Создана') | Q(status='Запущена')).count
        context['photo_blog'] = Blog.objects.all()[:3]

        return context

mailing/templates/mailing/includes/inc_catalog_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal a"><a href="{% url 'mailing:home' %}">New-Mailing</a></h5>
    <nav class="ms-5">

        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:home' %}">Блог</a>

        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:mailing_list' %}">Список рассылок</a>

        {% if perms.users.view_user%}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:client' %}">Пользователи</a>
        {%endif%}


        <a class="btn btn-success" href="{% url 'mailing:create' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus"
                 viewBox="0 0 16 16">
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
            </svg>
            Создать Рассылку</a>
        {% endif %}
    </nav>


    <div class="ms-auto p-2 bd-highlight">
        <div class="px-5">
            <div class="px-5">


                <div class="container ms-auto p-2 bd-highlight">
                    <div class="row">
                        <div class="col m-0 p-0">


                            <ul class="navbar-nav">
                                <li class="nav-item dropdown">
                                    {% if user.is_authenticated %}
                                    <a class="avatar" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                        {% if object.avatar %}
                                        <img class="img-avatar" src="/media/{{ object.avatar }}" width="45"/>
                                        {% else %}
                                        <img class="img-avatar" src="/media/users/no-profile.webp" width="45"/>
                                        {% endif %}
                                        <!--                            <span class="avatar-badge border bg-red-300 p-1"></span>-->
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Профиль</a></li>
                                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                                    </ul>

                                    {% else %}
                                    <a class="p-2 btn btn-outline-primary" href="{% url 'users:login'%}">Войти</a>
                                    </div>
                                    <div class="col">
                                        <a class="p-2 btn btn-outline-primary"
                                           href="{% url 'users:register'%}">Регистрация</a>
                                    </div>
                                    {% endif %}
                        </li>
                        </ul>
                    </div>
                    <div class="col m-0 p-0">
                        <div class="ms-auto p-2 bd-highlight">{{ user.email }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


</div>

<style>
    .a a{
        text-decoration: none;
        color: black;
    }

    .avatar {
        transition: transform 0.3s;
    }

    .avatar:hover {
        transform: scale(1.5);
    }

        .img-avatar:hover {
         outline: 2px solid #007bff; /* Параметры рамки */
         border-radius: 50px; /* Радиус скругления */
        }
</style>